project:
  type: website
  output-dir: _output
  resources:
    - graph_medium/stress/social_graph.json
    - graph_medium/stress/vsm_demo.json
    - assets
    - graph_big/visuals/fa2_graphbig.html
    - graph_big/visuals/fa2_categorygraph.html
    - graph_big/visuals/fa2_greygraph.html
    - graph_big/visuals/fa2_biggraph.json
    - graph_big/visuals/hairball.html
    - graph_big/visuals/umap_graph.html
    - graph_big/visuals/sfdp_graph.html
    - graph_big/visuals/graph_sfdp.json
    - graph_big/visuals/graph_umap.json
    - graph_big/visuals/hairball.json

website:
  title: "Graphdatenvisualisierung"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: small.qmd
        text: Kleiner Datensatz
      - href: medium.qmd
        text: Mittlerer Datensatz
      - href: big.qmd
        text: Großer Datensatz
      - href: gnn.qmd
        text: GNNs
      - href: cookbook.qmd
        text: Rezeptbuch

format:
  html:
    theme: flatly
    css:
      - styles.css
      - custom.css

