project:
  type: website
  output-dir: _output
  resources:
    - assets

website:
  title: "Graphdatenvisualisierung"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
