project:
  type: website
  output-dir: _output
  resources:
    - assets

website:
  title: "Graphdatenvisualisierung"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css

include-in-header:
  text: |
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont/dist/tabler-icons.min.css">
  
